(function(){const API='/api',listeners=new Set();let last=Number(sessionStorage.getItem('vyra-last-live-event')||0),online=false;async function json(url,options){let r=await fetch(API+url,{cache:'no-store',headers:{'Content-Type':'application/json'},...options});if(!r.ok)throw Error('Serverfel '+r.status);return r.json()}function emit(name,detail){dispatchEvent(new CustomEvent(name,{detail}));listeners.forEach(fn=>fn(detail))}async function status(){try{let d=await json('/status');if(!online){online=true;emit('vyra-server-status',d)}return d}catch(e){if(online){online=false;emit('vyra-server-offline',{error:e.message})}throw e}}function liveEventTrigger(e){let t=String(e.type||'').toLowerCase(),payload={username:e.username,name:e.name||e.username,gift:e.giftName,giftname:e.giftName,profileImage:e.profileImage,coins:e.coins,count:e.count,repeatcount:e.count,combo:e.count,value:e.name||e.giftName||e.username};
  if(t==='gift')return e.count>1?['giftCombo',payload]:['gift',payload];
  if(t==='follow')return['follow',payload];
  if(t==='member'||t==='subscribe')return['member',payload];
  if(t==='share')return['share',payload];
  if(t==='likes'||t==='like')return['likes',{...payload,value:e.count}];
  if(t==='chatcommand')return['chatCommand',{...payload,command:e.name,value:e.name}];
  if(t==='chat')return['chat',{...payload,comment:e.name,value:e.name}];
  return null}
async function poll(){try{let d=await json('/events?after='+last);for(let e of d.events||[]){last=Math.max(last,e.id||0);sessionStorage.setItem('vyra-last-live-event',last);localStorage.setItem('vyra-live-event',JSON.stringify(e));emit('vyra-live-event',e);if(typeof routeLiveBattleEvent==='function')routeLiveBattleEvent(e);let mapped=liveEventTrigger(e);if(mapped&&window.VyraActionEvent){window.VyraActionEvent.handleEvent(mapped[0],mapped[1]);if(mapped[0]==='member')window.VyraActionEvent.handleEvent('join',mapped[1])}}}catch{}finally{setTimeout(poll,650)}}window.VyraLive={status,connect:username=>json('/connect',{method:'POST',body:JSON.stringify({username})}),disconnect:()=>json('/disconnect',{method:'POST',body:'{}'}),send:event=>json('/events',{method:'POST',body:JSON.stringify(event)}),on(fn){listeners.add(fn);return()=>listeners.delete(fn)}};status().catch(()=>{});poll()})();
